export const quiz = [
  {
    number: "1",
    question: "What does the acronym GDGOC stand for?",
    answer: "Google Developer Groups on Campus",
    options: [
      "Google Development Software Cloud",
      "Google Developer Groups on Campus",
      "Global Developer Service Community",
      "General Developer Software Company",
    ],
    type: "GDGOC Community",
  },
  {
    number: "2",
    question: "What is the primary language used in Flutter?",
    answer: "Dart",
    options: ["Dart", "Python", "Java", "Kotlin"],
    type: "Flutter",
  },
  {
    number: "3",
    question: "What does the term 'CI/CD' stand for in cloud development?",
    answer: "Continuous Integration and Continuous Delivery",
    options: [
      "Continuous Integration and Continuous Deployment",
      "Code Integration and Continuous Development",
      "Continuous Integration and Continuous Delivery",
      "Cloud Integration and Continuous Deployment",
    ],
    type: "Cloud",
  },
  {
    number: "4",
    question: "Which widget is used to create scrollable lists in Flutter?",
    answer: "ListView",
    options: ["ListView", "GridView", "Stack", "Column"],
    type: "Flutter",
  },
  {
    number: "5",
    question: "Which service is offered by Google Cloud?",
    answer: "Compute Engine",
    options: ["Google Photos", "Gmail", "Compute Engine", "Google Drive"],
    type: "Cloud",
  },
  {
    number: "6",
    question: "What is the purpose of the setState function in Flutter?",
    answer: "Updates the UI when the state of the app changes",
    options: [
      "Updates the state of the app",
      "Initializes the app",
      "Fetches data from the server",
      "Saves data to the database",
    ],
    type: "Flutter",
  },
  {
    number: "7",
    question: "What is the core principle of cloud computing?",
    answer: "On-demand availability of computing resources",
    options: [
      "Fixed availability of resources",
      "On-demand availability of computing resources",
      "Manual resource allocation",
      "Shared hosting only",
    ],
    type: "Cloud",
  },
  {
    number: "8",
    question: "Which method is used to add interactivity in Flutter?",
    answer: "GestureDetector",
    options: ["Container", "GestureDetector", "Column", "Padding"],
    type: "Flutter",
  },
  {
    number: "9",
    question: "Which language is primarily used for web development?",
    answer: "JavaScript",
    options: ["JavaScript", "Python", "Java", "C++"],
    type: "Web Development",
  },
  {
    number: "10",
    question: "What does CSS stand for?",
    answer: "Cascading Style Sheets",
    options: [
      "Computer Style Sheets",
      "Cascading Style Sheets",
      "Creative Style Scripts",
      "Cascading Simple Sheets",
    ],
    type: "Web Development",
  },
  {
    number: "11",
    question: "Which of these is a cloud storage service?",
    answer: "Google Drive",
    options: ["Google Photos", "Google Drive", "Firebase", "Kubernetes"],
    type: "Cloud",
  },
  {
    number: "12",
    question: "What is the main function of a GDGOC Lead?",
    answer: "To organize and lead community activities",
    options: [
      "To lead cloud development",
      "To organize and lead community activities",
      "To build websites",
      "To teach coding",
    ],
    type: "GDGOC Community",
  },
  {
    number: "13",
    question: "Which is a key feature of cloud computing?",
    answer: "Scalability",
    options: [
      "Scalability",
      "Inflexibility",
      "Low availability",
      "Manual upgrades",
    ],
    type: "Cloud",
  },
  {
    number: "14",
    question: "Which company developed Flutter?",
    answer: "Google",
    options: ["Google", "Facebook", "Microsoft", "Amazon"],
    type: "Flutter",
  },
  {
    number: "15",
    question: "Which HTML tag is used to define a hyperlink?",
    answer: "<a>",
    options: ["<link>", "<a>", "<h>", "<p>"],
    type: "Web Development",
  },
  {
    number: "16",
    question: "What is a widget in Flutter?",
    answer: "A building block for UI elements",
    options: [
      "A backend framework",
      "A tool for building APIs",
      "A building block for UI elements",
      "A cloud service",
    ],
    type: "Flutter",
  },
  {
    number: "17",
    question: "Which of these is a NoSQL database?",
    answer: "MongoDB",
    options: ["MySQL", "SQL Server", "MongoDB", "PostgreSQL"],
    type: "Web Development",
  },
  {
    number: "18",
    question: "Which command is used to create a new Flutter project?",
    answer: "flutter create project_name",
    options: [
      "flutter create project_name",
      "flutter new project",
      "flutter init",
      "flutter start",
    ],
    type: "Flutter",
  },
  {
    number: "19",
    question: "What does CDN stand for?",
    answer: "Content Delivery Network",
    options: [
      "Central Data Network",
      "Content Delivery Network",
      "Content Data Node",
      "Cloud Delivery Network",
    ],
    type: "Cloud",
  },
  {
    number: "20",
    question: "Which method is used to update the state in Flutter?",
    answer: "setState",
    options: ["setState", "updateState", "changeState", "modifyState"],
    type: "Flutter",
  },
  {
    number: "21",
    question: "What is Firebase used for?",
    answer: "Real-time database and backend services",
    options: [
      "Hosting websites",
      "Real-time database and backend services",
      "Running scripts",
      "Storing files",
    ],
    type: "Web Development",
  },
  {
    number: "22",
    question: "Which of the following is a front-end framework?",
    answer: "React",
    options: ["React", "Node.js", "MongoDB", "Django"],
    type: "Web Development",
  },
  {
    number: "23",
    question: "Which platform is known for container orchestration?",
    answer: "Kubernetes",
    options: ["Kubernetes", "Docker", "Terraform", "Ansible"],
    type: "Cloud",
  },
  {
    number: "24",
    question: "What is the purpose of GitHub?",
    answer: "Code hosting and collaboration",
    options: [
      "Building websites",
      "Code hosting and collaboration",
      "Creating databases",
      "Storing images",
    ],
    type: "Web Development",
  },
  {
    number: "25",
    question: "Which cloud platform offers Lambda services?",
    answer: "AWS",
    options: ["AWS", "Google Cloud", "Azure", "IBM Cloud"],
    type: "Cloud",
  },
];

export const funFacts = [
  "The longest quiz ever created consisted of 1,000 questions.",
  "Quizzes can improve your memory and cognitive skills.",
  "The first known quiz was published in a British newspaper in 1861.",
  "Multiple-choice questions were first used in the 1920s.",
  "The term 'quiz' originally referred to a practical joke.",
  "Online quizzes became popular in the early 2000s.",
  "Quizzes can be a great tool for learning and retention.",
  "Trivia night at pubs started in the late 1980s.",
  "There are quiz competitions held globally, including the Quiz Olympiad.",
  "Some quizzes can be used to assess personality traits.",
  "GDSC operates in over 100 countries, making it a truly global initiative.",
  "It empowers students to develop their technical skills through hands-on projects.",
  "GDSC clubs focus on real-world applications of technology, enhancing learning.",
  "Students gain access to Google resources and tools to aid their projects.",
  "GDSC hosts workshops and seminars led by industry experts and experienced peers.",
  "Members can participate in hackathons, fostering teamwork and creativity.",
  "GDSC encourages open-source contributions, allowing students to collaborate on real projects.",
  "It's a great platform for networking with peers and industry professionals.",
  "GDSC collaborates with local communities to tackle real-world problems.",
  "Members can gain Google Cloud certifications through GDSC resources.",
  "GDSC organizes events like DevFests, bringing together students and developers.",
  "Through GDSC, students can build portfolios that showcase their skills and projects.",
  "GDSC members can access exclusive Google workshops and learning materials.",
  "It provides a supportive environment for learning and skill development.",
  "GDSC promotes diversity in tech by encouraging participation from underrepresented groups.",
  "The initiative fosters a culture of innovation and creativity among students.",
  "GDSC clubs often partner with local companies for internships and job opportunities.",
  "Members have the chance to present their projects at global events.",
  "GDSC offers mentorship programs where experienced developers guide students.",
  "Participating in GDSC can enhance resumes and job prospects for students.",
  "GDSC encourages collaboration across disciplines, merging tech with arts and sciences.",
  "Students learn to solve complex problems through real-world projects.",
  "GDSC provides a platform for students to lead and organize tech events.",
  "Members can join study groups to prepare for technical interviews.",
  "GDSC promotes lifelong learning and continuous improvement in tech skills.",
  "The initiative often invites guest speakers from top tech companies.",
  "GDSC helps students stay updated on the latest technologies and trends.",
  "Members can access coding challenges and contests to sharpen their skills.",
  "GDSC emphasizes the importance of community engagement and social impact.",
  "It nurtures soft skills like communication, teamwork, and leadership.",
  "GDSC clubs often conduct coding bootcamps to help beginners.",
  "Students can participate in Google’s initiatives like Summer of Code.",
  "GDSC encourages members to share their knowledge through blogs and talks.",
  "Members often collaborate with local schools to promote coding education.",
  "GDSC provides opportunities for students to work on impactful projects.",
  "It inspires students to think outside the box and innovate.",
  "GDSC helps students to connect with alumni who have succeeded in tech.",
  "Members can explore different tech stacks and frameworks through workshops.",
  "GDSC encourages participation in global competitions like Code Jam.",
  "Clubs often celebrate achievements and milestones, fostering a sense of community.",
  "GDSC provides resources for building mobile and web applications.",
  "It offers a chance to learn about cloud computing and its applications.",
  "GDSC helps students develop a growth mindset and resilience.",
  "Members can learn about design thinking and user experience principles.",
  "GDSC promotes ethical tech practices and responsible coding.",
  "The initiative helps build confidence in public speaking and presentations.",
  "Students can form study groups for various tech certifications.",
  "GDSC organizes fun events like game nights to build camaraderie.",
  "Members often engage in peer-to-peer learning and knowledge sharing.",
  "GDSC collaborates with NGOs for projects that benefit society.",
  "It offers students a platform to experiment and prototype new ideas.",
  "GDSC emphasizes the importance of mental health and well-being in tech.",
  "Members are encouraged to pursue passion projects alongside their studies.",
  "GDSC fosters an inclusive environment where everyone is welcome.",
  "Students can leverage GDSC for career guidance and job placement support.",
  "The initiative encourages creativity and innovation in solving tech challenges.",
];
