export const clothingProducts = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    category: "Tops",
    price: 499,
    size: ["S", "M", "L", "XL"],
    color: ["White", "Black", "Gray"],
    inStock: true,
    rating: 2.5,
  },
  {
    id: 2,
    name: "Denim Jacket",
    category: "Jackets",
    price: 1999,
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    inStock: true,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Slim Fit Jeans",
    category: "Bottoms",
    price: 1499,
    size: ["28", "30", "32", "34", "36"],
    color: ["Blue", "Black"],
    inStock: false,
    rating: 4.2,
  },
  {
    id: 4,
    name: "Summer Dress",
    category: "Dresses",
    price: 1799,
    size: ["S", "M", "L"],
    color: ["Red", "Yellow", "Pink"],
    inStock: true,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Hooded Sweatshirt",
    category: "Sweatshirts",
    price: 1299,
    size: ["S", "M", "L", "XL"],
    color: ["Gray", "Green", "Black"],
    inStock: true,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Cargo Pants",
    category: "Bottoms",
    price: 1599,
    size: ["30", "32", "34", "36"],
    color: ["Khaki", "Olive", "Black"],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 7,
    name: "Floral Print Skirt",
    category: "Skirts",
    price: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Green"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 8,
    name: "Leather Jacket",
    category: "Jackets",
    price: 2999,
    size: ["M", "L", "XL"],
    color: ["Black", "Brown"],
    inStock: true,
    rating: 4.9,
  },
];
