function importAll(r) {
  return r.keys().map(r);
}

const images = importAll(
  require.context("../../assets/Clothing/", false, /\.(png|jpe?g|JPG|webp)$/)
);

export const clothingProducts = [
  {
    id: 1,
    img: images[0],
    name: "Classic White T-Shirt",
    category: "Tops",
    mrp: 699,
    currentPrice: 499,
    size: ["S", "M", "L", "XL"],
    color: ["White", "Black", "Gray"],
    inStock: true,
    rating: 2.5,
  },
  {
    id: 2,
    img: images[1],
    name: "Denim Jacket",
    category: "Jackets",
    mrp: 2499,
    currentPrice: 1999,
    size: ["M", "L", "XL"],
    color: ["Blue", "Black"],
    inStock: true,
    rating: 4.8,
  },
  {
    id: 3,
    img: images[2],
    name: "Slim Fit Jeans",
    category: "Bottoms",
    mrp: 1799,
    currentPrice: 1499,
    size: ["28", "30", "32", "34", "36"],
    color: ["Blue", "Black"],
    inStock: false,
    rating: 4.2,
  },
  {
    id: 4,
    img: images[3],
    name: "Summer Dress",
    category: "Dresses",
    mrp: 2199,
    currentPrice: 1799,
    size: ["S", "M", "L"],
    color: ["Red", "Yellow", "Pink"],
    inStock: true,
    rating: 4.7,
  },
  {
    id: 5,
    img: images[4],
    name: "Hooded Sweatshirt",
    category: "Sweatshirts",
    mrp: 1599,
    currentPrice: 1299,
    size: ["S", "M", "L", "XL"],
    color: ["Gray", "Green", "Black"],
    inStock: true,
    rating: 4.6,
  },
  {
    id: 6,
    img: images[5],
    name: "Cargo Pants",
    category: "Bottoms",
    mrp: 1899,
    currentPrice: 1599,
    size: ["30", "32", "34", "36"],
    color: ["Khaki", "Olive", "Black"],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 7,
    img: images[6],
    name: "Floral Print Skirt",
    category: "Skirts",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Green"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 8,
    img: images[7],
    name: "Leather Jacket",
    category: "Jackets",
    mrp: 3499,
    currentPrice: 2999,
    size: ["M", "L", "XL"],
    color: ["Black", "Brown"],
    inStock: true,
    rating: 4.9,
  },
];
