function importAll(r) {
  return r.keys().map(r);
}

const images = importAll(
  require.context("../../assets/Clothing/", false, /\.(png|jpe?g|JPG|webp)$/)
);

export const clothingProducts = [
  {
    id: 1,
    img: images[0],
    name: "Every One Is a Ferrari Fan",
    category: "Oversize tshirt",
    mrp: 1199,
    currentPrice: 599,
    size: ["S", "M", "L", "XL"],
    color: ["White", "Black", "Red"],
    inStock: true,
    rating: 2.5,
  },
  {
    id: 2,
    img: images[1],
    name: "God's Plan",
    category: "Oversize tshirt",
    mrp: 1199,
    currentPrice: 699,
    size: ["M", "L", "XL"],
    color: ["White", "Black"],
    inStock: true,
    rating: 4.8,
  },
  {
    id: 3,
    img: images[2],
    name: "Make Money Not Friends",
    category: "Oversize tshirt",
    mrp: 999,
    currentPrice: 499,
    size: ["28", "30", "32", "34", "36"],
    color: ["White", "Black"],
    inStock: false,
    rating: 4.2,
  },
  {
    id: 4,
    img: images[3],
    name: "Bad Boy's Club",
    category: "Oversize tshirt",
    mrp: 799,
    currentPrice: 399,
    size: ["S", "M", "L"],
    color: ["Blue", "White", "Black"],
    inStock: true,
    rating: 4.7,
  },
  {
    id: 5,
    img: images[4],
    name: "Surviving Every Minute",
    category: "Oversize tshirt",
    mrp: 899,
    currentPrice: 499,
    size: ["S", "M", "L", "XL"],
    color: ["White", "Black"],
    inStock: true,
    rating: 4.6,
  },
  {
    id: 6,
    img: images[5],
    name: "Social Introvert",
    category: "Oversize tshirt",
    mrp: 999,
    currentPrice: 699,
    size: ["30", "32", "34", "36"],
    color: ["Black", "White"],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 7,
    img: images[6],
    name: "Grove St 4 life",
    category: "GTA San Merch",
    mrp: 1299,
    currentPrice: 999,
    size: ["S", "M", "L"],
    color: ["White", "Blue", "Black"],
    inStock: false,
    rating: 4.1,
  },
  {
    id: 8,
    img: images[7],
    name: "Wasted",
    category: "GTA San Merch",
    mrp: 3499,
    currentPrice: 2999,
    size: ["M", "L", "XL"],
    color: ["Black", "Brown"],
    inStock: true,
    rating: 4.9,
  },
];
